# Generated by Django 2.1 on 2021-03-27 19:03

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=128)),
                ('item', models.CharField(max_length=256)),
                ('item_name', models.SlugField(max_length=256)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('about_item', models.CharField(max_length=24)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('condition', models.CharField(choices=[('good condition', 'Good Condition'), ('very good condition', 'Very Good Conditon')], default='good condition', max_length=20)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
    ]
