# Generated by Django 2.1 on 2021-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210328_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='about_item',
            field=models.CharField(max_length=18),
        ),
    ]
