# Generated by Django 2.1 on 2021-03-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210328_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.CharField(max_length=18),
        ),
    ]
